---
# ========================================
# Service Discovery - For Dynamic AWX Inventories
# Works with inventories created via API
# ========================================

- name: Run All Service Discovery Playbooks
  hosts: all  # This will use ALL hosts from the AWX inventory
  gather_facts: yes
  become: yes
  
  tasks:
    - name: Display execution information
      debug:
        msg: |
          ========================================
          Starting Complete Service Discovery
          ========================================
          Target: {{ inventory_hostname }}
          IP: {{ ansible_host }}
          User: {{ ansible_user }}
          ========================================

# Import all discovery playbooks
- import_playbook: Service_discovery/Middleware/Apache/apache_discovery.yml
  tags: [middleware, apache]

- import_playbook: Service_discovery/Middleware/Nginx/nginx_discovery.yml
  tags: [middleware, nginx]

- import_playbook: Service_discovery/Middleware/Tomcat/tomcat_discovery.yml
  tags: [middleware, tomcat]

- import_playbook: Service_discovery/DB/Mysql/mysql_discovery.yml
  tags: [database, mysql]

- import_playbook: Service_discovery/DB/Postgres/postgres_discovery.yml
  tags: [database, postgres]

- import_playbook: Service_discovery/DB/Mongodb/mongodb_discovery.yml
  tags: [database, mongodb]

# ========================================
# Collect Results and Send to Webhook API
# ========================================
- name: Collect Results and Send to Webhook API
  hosts: localhost
  gather_facts: yes
  become: no
  
  vars:
    # Default webhook configuration (can be overridden via extra_vars)
    webhook_api_url: "{{ webhook_api_url | default('https://filecompression.acc.ltd/ServiceDiscovery/api/v1/servicediscovery/ansiblecall') }}"
    webhook_timeout: 30
    webhook_retries: 3
    webhook_retry_delay: 5
    webhook_expected_status_codes: [200, 201, 202]
    webhook_validate_certs: false
    discovery_job_name: "Service Discovery"
    discovery_execution_node: "{{ ansible_hostname }}"
    
  tasks:
    - name: Execute discovery collection and webhook delivery
      block:
        # Collect All Discovery Results
        - name: Collect Apache discoveries from all hosts
          set_fact:
            apache_results: "{{ groups['all'] | map('extract', hostvars, 'apache_discovery_json') | select('defined') | list }}"
          
        - name: Collect Nginx discoveries from all hosts
          set_fact:
            nginx_results: "{{ groups['all'] | map('extract', hostvars, 'nginx_discovery_json') | select('defined') | list }}"
          
        - name: Collect Tomcat discoveries from all hosts
          set_fact:
            tomcat_results: "{{ groups['all'] | map('extract', hostvars, 'tomcat_discovery_json') | select('defined') | list }}"
          
        - name: Collect MySQL discoveries from all hosts
          set_fact:
            mysql_results: "{{ groups['all'] | map('extract', hostvars, 'mysql_discovery_json') | select('defined') | list }}"
          
        - name: Collect PostgreSQL discoveries from all hosts
          set_fact:
            postgres_results: "{{ groups['all'] | map('extract', hostvars, 'postgres_discovery_json') | select('defined') | list }}"
          
        - name: Collect MongoDB discoveries from all hosts
          set_fact:
            mongodb_results: "{{ groups['all'] | map('extract', hostvars, 'mongodb_discovery_json') | select('defined') | list }}"

        - name: Calculate total instances
          set_fact:
            total_apache: "{{ apache_results | map(attribute='discovery') | flatten | length }}"
            total_nginx: "{{ nginx_results | map(attribute='discovery') | flatten | length }}"
            total_tomcat: "{{ tomcat_results | map(attribute='discovery') | flatten | length }}"
            total_mysql: "{{ mysql_results | map(attribute='discovery') | flatten | length }}"
            total_postgres: "{{ postgres_results | map(attribute='discovery') | flatten | length }}"
            total_mongodb: "{{ mongodb_results | map(attribute='discovery') | flatten | length }}"

        - name: Build combined results payload
          set_fact:
            combined_payload:
              job_info:
                job_id: "{{ tower_job_id | default(ansible_date_time.epoch) }}"
                batch_id: "{{ batch_id | default('N/A') }}"
                job_name: "{{ tower_job_template_name | default(discovery_job_name) }}"
                execution_time: "{{ ansible_date_time.iso8601 }}"
                execution_node: "{{ discovery_execution_node }}"
                status: "success"
              discovery_results:
                middleware:
                  apache:
                    total_servers: "{{ apache_results | length }}"
                    total_instances: "{{ total_apache }}"
                    servers: "{{ apache_results }}"
                  nginx:
                    total_servers: "{{ nginx_results | length }}"
                    total_instances: "{{ total_nginx }}"
                    servers: "{{ nginx_results }}"
                  tomcat:
                    total_servers: "{{ tomcat_results | length }}"
                    total_instances: "{{ total_tomcat }}"
                    servers: "{{ tomcat_results }}"
                database:
                  mysql:
                    total_servers: "{{ mysql_results | length }}"
                    total_instances: "{{ total_mysql }}"
                    servers: "{{ mysql_results }}"
                  postgresql:
                    total_servers: "{{ postgres_results | length }}"
                    total_instances: "{{ total_postgres }}"
                    servers: "{{ postgres_results }}"
                  mongodb:
                    total_servers: "{{ mongodb_results | length }}"
                    total_instances: "{{ total_mongodb }}"
                    servers: "{{ mongodb_results }}"
              summary:
                total_middleware_instances: "{{ total_apache | int + total_nginx | int + total_tomcat | int }}"
                total_database_instances: "{{ total_mysql | int + total_postgres | int + total_mongodb | int }}"
                total_servers_scanned: "{{ groups['all'] | length }}"
                discovery_breakdown:
                  - service: "Apache"
                    instances: "{{ total_apache }}"
                  - service: "Nginx"
                    instances: "{{ total_nginx }}"
                  - service: "Tomcat"
                    instances: "{{ total_tomcat }}"
                  - service: "MySQL"
                    instances: "{{ total_mysql }}"
                  - service: "PostgreSQL"
                    instances: "{{ total_postgres }}"
                  - service: "MongoDB"
                    instances: "{{ total_mongodb }}"

        - name: Display combined payload
          debug:  
            msg: |
              ========================================
              Combined Discovery Payload  
              {{ combined_payload }}
              ========================================
         
        - name: Send combined results to webhook API
          uri:
            url: "{{ webhook_api_url }}"
            method: POST
            body_format: json
            headers:
              Content-Type: "application/json"
              X-Job-ID: "{{ tower_job_id | default('manual') }}"
              X-Timestamp: "{{ ansible_date_time.date }}T{{ ansible_date_time.time }}+05:30 }}"
            body: "{{ combined_payload }}"
            status_code: "{{ webhook_expected_status_codes }}"
            timeout: "{{ webhook_timeout }}"
            validate_certs: "{{ webhook_validate_certs }}"
            return_content: yes
          register: webhook_response
          until: webhook_response.status in webhook_expected_status_codes
          retries: "{{ webhook_retries }}"
          delay: "{{ webhook_retry_delay }}"
          
        - name: Display webhook response
          debug:
            msg: |
              ========================================
              Webhook API Response
              ========================================
              Status: {{ webhook_response.status | default('SKIPPED') }}
              Response: {{ webhook_response.json | default(webhook_response.content) | default('No response') }}
              ========================================

        - name: Display summary
          debug:
            msg: |
              ========================================
              Service Discovery Completed Successfully
              ========================================
              Total Servers: {{ groups['all'] | length }}
              Total Middleware: {{ total_apache | int + total_nginx | int + total_tomcat | int }}
              Total Database: {{ total_mysql | int + total_postgres | int + total_mongodb | int }}
              
              Results sent to: {{ webhook_api_url }}
              Webhook Status: {{ webhook_response.status | default('Not Sent') }}
              ========================================

      rescue:
        - name: Build failure payload
          set_fact:
            failure_payload:
              job_info:
                job_id: "{{ tower_job_id | default(ansible_date_time.epoch) }}"
                batch_id: "{{ batch_id | default('N/A') }}"
                job_name: "{{ tower_job_template_name | default(discovery_job_name) }}"
                execution_time: "{{ ansible_date_time.date }}T{{ ansible_date_time.time }}+05:30 }}"
                status: "failed"
              error:
                message: "Service discovery failed"
                task: "{{ ansible_failed_task.name | default('Unknown') }}"
                error_details: "{{ ansible_failed_result | default({}) }}"

        - name: Send failure notification to webhook
          uri:
            url: "{{ webhook_api_url }}"
            method: POST
            body_format: json
            headers:
              Content-Type: "application/json"
              X-Job-ID: "{{ tower_job_id | default('manual') }}"
              X-Status: "FAILED"
            body: "{{ failure_payload }}"
            status_code: "{{ webhook_expected_status_codes }}"
            timeout: 30
            validate_certs: "{{ webhook_validate_certs }}"
          failed_when: false

        # - name: Fail the playbook with error details
        #   fail:
        #     msg: |
        #       Discovery job failed!
        #       Task: {{ ansible_failed_task.name | default('Unknown') }}
        #       Error: {{ ansible_failed_result.msg | default('Unknown error') }}
        #       Failure notification sent to webhook.

        - name: Display failure message (but DO NOT FAIL)
          debug:
            msg: |
              ========================================
              DISCOVERY FAILED
              ========================================
              Task Failed: {{ ansible_failed_task.name | default('Unknown') }}
              Error: {{ ansible_failed_result.msg | default('Unknown error') }}
              Failure notification sent to webhook.
              ========================================
