---
# ========================================
# IBM WebSphere Discovery Playbook
# Process-First Approach with JSON Output
# WEBHOOK ONLY - No File Saving
# ========================================

- name: IBM WebSphere Discovery - Process-First Approach
  hosts: all
  become: yes
  gather_facts: yes
  
  tasks:
    # ========================================
    # PREREQUISITE: Detect Available Tools
    # ========================================
    - name: Detect network tool
      shell: |
        if command -v ss >/dev/null 2>&1; then echo "ss"
        elif command -v netstat >/dev/null 2>&1; then echo "netstat"
        elif command -v lsof >/dev/null 2>&1; then echo "lsof"
        else echo "none"; fi
      register: network_tool
      changed_when: false
      failed_when: false

    # ========================================
    # STEP 1: GET ALL WEBSPHERE PROCESS DATA IN SINGLE CALL
    # ========================================
    - name: Get all WebSphere process data in single optimized call
      shell: |
        #!/bin/bash
        ps -eo pid,cmd | grep -E '[j]ava.*[Ww]as\.(home|install\.|server\.name)' | \
        awk '{
          pid=$1
          # Extract key WebSphere properties from command line
          server_name=""
          cell_name=""
          node_name=""
          was_home=""
          profile_path=""
          
          # Look for server name
          if (match($0, /-Dwas\.server\.name=([^ ]+)/, arr)) server_name=arr[1]
          if (match($0, /-Dserver\.name=([^ ]+)/, arr)) server_name=arr[1]
          
          # Look for cell name
          if (match($0, /-Dwas\.cell\.name=([^ ]+)/, arr)) cell_name=arr[1]
          if (match($0, /-Dcell\.name=([^ ]+)/, arr)) cell_name=arr[1]
          
          # Look for node name
          if (match($0, /-Dwas\.node\.name=([^ ]+)/, arr)) node_name=arr[1]
          if (match($0, /-Dnode\.name=([^ ]+)/, arr)) node_name=arr[1]
          
          # Look for WAS home
          if (match($0, /-Dwas\.install\.root=([^ ]+)/, arr)) was_home=arr[1]
          if (match($0, /was\.install\.root=([^ ]+)/, arr)) was_home=arr[1]
          
          # Look for profile path
          if (match($0, /-Duser\.install\.root=([^ ]+)/, arr)) profile_path=arr[1]
          if (match($0, /user\.install\.root=([^ ]+)/, arr)) profile_path=arr[1]
          
          print pid":"server_name":"cell_name":"node_name":"was_home":"profile_path
        }' > /tmp/was_processes.tmp
        
        if [ -s /tmp/was_processes.tmp ]; then
          echo "PROCESSES:"
          cat /tmp/was_processes.tmp | sort -u
          echo "PROFILES:"
          awk -F: '{if($6!="") print $6}' /tmp/was_processes.tmp | sort -u
          echo "WASHOMES:"
          awk -F: '{if($5!="") print $5}' /tmp/was_processes.tmp | sort -u
        fi
        rm -f /tmp/was_processes.tmp
      register: was_process_data
      changed_when: false
      failed_when: false

    - name: Parse process data and set variables
      set_fact:
        running_was_processes: "{{ was_process_data.stdout_lines | select('match', '^[0-9]+:') | list }}"
        unique_profiles: "{{ was_process_data.stdout_lines | select('match', '^/.*profiles') | list | unique }}"
        unique_was_homes: "{{ was_process_data.stdout_lines | select('match', '^/.*WebSphere') | list | unique }}"

    # ========================================
    # STEP 2: FIND ALL WEBSPHERE INSTALLATIONS (including stopped servers)
    # ========================================
    - name: Find all WebSphere installations on system
      shell: |
        #!/bin/bash
        # Common WebSphere installation paths
        find /opt /usr/local /app /opt/IBM /usr/IBM -type f -name "versionInfo.sh" 2>/dev/null | \
        while read version_file; do
          was_home=$(dirname $(dirname "$version_file"))
          echo "$was_home"
        done | sort -u
      register: all_was_installations
      changed_when: false
      failed_when: false

    - name: Combine discovered WAS homes
      set_fact:
        all_was_homes: "{{ (unique_was_homes + all_was_installations.stdout_lines) | select | unique | list }}"

    # ========================================
    # STEP 3: COLLECT DATA FOR EACH WAS INSTALLATION
    # ========================================
    - name: Collect all data for each WebSphere installation
      shell: |
        #!/bin/bash
        WAS_HOME="{{ item }}"
        
        # Get version information
        VERSION="unknown"
        VERSION_FILE="$WAS_HOME/bin/versionInfo.sh"
        if [ -x "$VERSION_FILE" ]; then
          VERSION=$("$VERSION_FILE" 2>/dev/null | grep "Version" | head -1 | awk '{print $2}')
        fi
        
        # If version not found, try properties file
        if [ "$VERSION" = "unknown" ]; then
          PROPS_FILE="$WAS_HOME/properties/version/WAS.product"
          if [ -f "$PROPS_FILE" ]; then
            VERSION=$(grep "^version=" "$PROPS_FILE" 2>/dev/null | cut -d= -f2)
          fi
        fi
        
        # Get product name/edition
        PRODUCT="WebSphere Application Server"
        if [ -f "$WAS_HOME/properties/version/WAS.product" ]; then
          PRODUCT=$(grep "^name=" "$WAS_HOME/properties/version/WAS.product" 2>/dev/null | cut -d= -f2 | sed 's/IBM //')
        fi
        
        # Find all profiles
        PROFILES_DIR="$WAS_HOME/profiles"
        PROFILES=""
        if [ -d "$PROFILES_DIR" ]; then
          PROFILES=$(find "$PROFILES_DIR" -maxdepth 1 -type d ! -name "profiles" -printf "%f," 2>/dev/null | sed 's/,$//')
        fi
        
        # Get installation path and home
        INSTALL_PATH="$WAS_HOME"
        
        # Output delimited format
        echo "WAS_HOME=$WAS_HOME|||VERSION=$VERSION|||PRODUCT=$PRODUCT|||PROFILES=$PROFILES|||INSTALL_PATH=$INSTALL_PATH"
      args:
        executable: /bin/bash
      register: was_installation_data
      changed_when: false
      failed_when: false
      loop: "{{ all_was_homes }}"
      when: all_was_homes | length > 0

    # ========================================
    # STEP 4: COLLECT DATA FOR EACH PROFILE AND SERVER
    # ========================================
    - name: Find all profiles and servers
      shell: |
        #!/bin/bash
        WAS_HOME="{{ item }}"
        PROFILES_DIR="$WAS_HOME/profiles"
        
        if [ ! -d "$PROFILES_DIR" ]; then
          exit 0
        fi
        
        find "$PROFILES_DIR" -maxdepth 1 -type d ! -name "profiles" 2>/dev/null | while read PROFILE_PATH; do
          PROFILE_NAME=$(basename "$PROFILE_PATH")
          
          # Find servers in this profile
          SERVERS_DIR="$PROFILE_PATH/config/cells"
          if [ -d "$SERVERS_DIR" ]; then
            find "$SERVERS_DIR" -name "server.xml" 2>/dev/null | while read SERVER_XML; do
              # Extract cell, node, server from path
              # Path format: profiles/ProfileName/config/cells/CellName/nodes/NodeName/servers/ServerName/server.xml
              CELL_NAME=$(echo "$SERVER_XML" | awk -F'/cells/' '{print $2}' | cut -d'/' -f1)
              NODE_NAME=$(echo "$SERVER_XML" | awk -F'/nodes/' '{print $2}' | cut -d'/' -f1)
              SERVER_NAME=$(echo "$SERVER_XML" | awk -F'/servers/' '{print $2}' | cut -d'/' -f1)
              
              echo "$WAS_HOME|||$PROFILE_PATH|||$PROFILE_NAME|||$CELL_NAME|||$NODE_NAME|||$SERVER_NAME|||$SERVER_XML"
            done
          fi
        done
      args:
        executable: /bin/bash
      register: was_servers_data
      changed_when: false
      failed_when: false
      loop: "{{ all_was_homes }}"
      when: all_was_homes | length > 0

    # ========================================
    # STEP 5: COLLECT DETAILED DATA FOR EACH SERVER
    # ========================================
    - name: Collect detailed data for each WebSphere server
      shell: |
        #!/bin/bash
        WAS_HOME="{{ item.split('|||')[0] }}"
        PROFILE_PATH="{{ item.split('|||')[1] }}"
        PROFILE_NAME="{{ item.split('|||')[2] }}"
        CELL_NAME="{{ item.split('|||')[3] }}"
        NODE_NAME="{{ item.split('|||')[4] }}"
        SERVER_NAME="{{ item.split('|||')[5] }}"
        SERVER_XML="{{ item.split('|||')[6] }}"
        
        # Check if server is running
        PID=""
        STATUS="stopped"
        for proc in {{ running_was_processes | join(' ') }}; do
          proc_server=$(echo "$proc" | cut -d: -f2)
          proc_cell=$(echo "$proc" | cut -d: -f3)
          proc_node=$(echo "$proc" | cut -d: -f4)
          proc_pid=$(echo "$proc" | cut -d: -f1)
          
          if [ "$proc_server" = "$SERVER_NAME" ] && [ "$proc_cell" = "$CELL_NAME" ] && [ "$proc_node" = "$NODE_NAME" ]; then
            PID="$proc_pid"
            STATUS="running"
            break
          fi
        done
        
        # Get ports from serverindex.xml
        SERVERINDEX="$PROFILE_PATH/config/cells/$CELL_NAME/nodes/$NODE_NAME/serverindex.xml"
        PORTS=""
        CONFIG_PORTS=""
        
        if [ -f "$SERVERINDEX" ]; then
          CONFIG_PORTS=$(grep -A 50 "serverName=\"$SERVER_NAME\"" "$SERVERINDEX" 2>/dev/null | \
            grep -oP 'port="\K[0-9]+' | sort -u | paste -sd, -)
        fi
        
        # If server is running, get actual listening ports
        if [ -n "$PID" ]; then
          case "{{ network_tool.stdout }}" in
            ss)
              PORTS=$(ss -ltnp 2>/dev/null | grep "pid=$PID" | awk '{print $4}' | awk -F: '{print $NF}' | sort -u | paste -sd, -)
              ;;
            netstat)
              PORTS=$(netstat -tulnp 2>/dev/null | grep "/$PID/" | awk '{print $4}' | awk -F: '{print $NF}' | sort -u | paste -sd, -)
              ;;
            lsof)
              PORTS=$(lsof -p $PID -i -P -n 2>/dev/null | grep LISTEN | awk '{print $9}' | awk -F: '{print $NF}' | sort -u | paste -sd, -)
              ;;
          esac
        fi
        
        # Get run user
        RUN_USER="unknown"
        if [ -n "$PID" ]; then
          RUN_USER=$(ps -p $PID -o user= 2>/dev/null)
        elif [ -f "$PROFILE_PATH/logs/$SERVER_NAME/$SERVER_NAME.pid" ]; then
          OLD_PID=$(cat "$PROFILE_PATH/logs/$SERVER_NAME/$SERVER_NAME.pid" 2>/dev/null)
          RUN_USER=$(ps -p $OLD_PID -o user= 2>/dev/null)
        fi
        
        if [ -z "$RUN_USER" ] || [ "$RUN_USER" = "" ]; then
          RUN_USER=$(stat -c %U "$PROFILE_PATH" 2>/dev/null)
        fi
        [ -z "$RUN_USER" ] && RUN_USER="unknown"
        
        # Get log directory
        LOG_DIR="$PROFILE_PATH/logs/$SERVER_NAME"
        
        # Get server type (application server, deployment manager, node agent, etc.)
        SERVER_TYPE="appserver"
        if [[ "$SERVER_NAME" == *"dmgr"* ]] || [[ "$SERVER_NAME" == *"Dmgr"* ]]; then
          SERVER_TYPE="deployment_manager"
        elif [[ "$SERVER_NAME" == "nodeagent"* ]] || [[ "$SERVER_NAME" == "NodeAgent"* ]]; then
          SERVER_TYPE="node_agent"
        fi
        
        # Get JVM heap settings if running
        JVM_HEAP="unknown"
        if [ -n "$PID" ]; then
          JVM_HEAP=$(ps -p $PID -o args= 2>/dev/null | grep -oP '\-Xmx[^ ]+|\-Xms[^ ]+' | paste -sd' ')
        fi
        [ -z "$JVM_HEAP" ] && JVM_HEAP="unknown"
        
        [ -z "$PORTS" ] && PORTS="none"
        [ -z "$CONFIG_PORTS" ] && CONFIG_PORTS="none"
        
        echo "WAS_HOME=$WAS_HOME|||PROFILE_PATH=$PROFILE_PATH|||PROFILE_NAME=$PROFILE_NAME|||CELL=$CELL_NAME|||NODE=$NODE_NAME|||SERVER=$SERVER_NAME|||PID=$PID|||STATUS=$STATUS|||PORTS=$PORTS|||CONFIG_PORTS=$CONFIG_PORTS|||RUN_USER=$RUN_USER|||LOG_DIR=$LOG_DIR|||SERVER_XML=$SERVER_XML|||SERVER_TYPE=$SERVER_TYPE|||JVM_HEAP=$JVM_HEAP"
      args:
        executable: /bin/bash
      register: was_server_details
      changed_when: false
      failed_when: false
      loop: "{{ was_servers_data.results | map(attribute='stdout_lines') | flatten | list }}"
      when:
        - was_servers_data is defined
        - was_servers_data.results is defined

    # ========================================
    # STEP 6: PARSE AND BUILD INSTANCES IN JSON FORMAT
    # ========================================
    - name: Initialize discovery array
      set_fact:
        discovery_array: []

    - name: Build installation lookup map
      set_fact:
        installation_map: "{{ installation_map | default({}) | combine({item.item: installation_info}) }}"
      vars:
        data_line: "{{ item.stdout }}"
        installation_info:
          version: "{{ data_line | regex_replace('.*VERSION=([^|]+).*', '\\1') | default('unknown') }}"
          product: "{{ data_line | regex_replace('.*PRODUCT=([^|]+).*', '\\1') | default('unknown') }}"
      loop: "{{ was_installation_data.results }}"
      when:
        - was_installation_data is defined
        - was_installation_data.results is defined
        - item.stdout is defined

    - name: Parse and build JSON formatted instances
      set_fact:
        discovery_array: "{{ discovery_array + [json_instance] }}"
      vars:
        data_line: "{{ item.stdout }}"
        was_home: "{{ data_line | regex_replace('.*WAS_HOME=([^|]+).*', '\\1') | default('unknown') }}"
        profile_path: "{{ data_line | regex_replace('.*PROFILE_PATH=([^|]+).*', '\\1') | default('unknown') }}"
        profile_name: "{{ data_line | regex_replace('.*PROFILE_NAME=([^|]+).*', '\\1') | default('unknown') }}"
        cell_name: "{{ data_line | regex_replace('.*CELL=([^|]+).*', '\\1') | default('unknown') }}"
        node_name: "{{ data_line | regex_replace('.*NODE=([^|]+).*', '\\1') | default('unknown') }}"
        server_name: "{{ data_line | regex_replace('.*SERVER=([^|]+).*', '\\1') | default('unknown') }}"
        pid_raw: "{{ data_line | regex_replace('.*PID=([^|]+).*', '\\1') | default('') }}"
        status: "{{ data_line | regex_replace('.*STATUS=([^|]+).*', '\\1') | default('unknown') }}"
        ports_raw: "{{ data_line | regex_replace('.*PORTS=([^|]+).*', '\\1') | default('none') }}"
        config_ports_raw: "{{ data_line | regex_replace('.*CONFIG_PORTS=([^|]+).*', '\\1') | default('none') }}"
        run_user: "{{ data_line | regex_replace('.*RUN_USER=([^|]+).*', '\\1') | default('unknown') }}"
        log_dir: "{{ data_line | regex_replace('.*LOG_DIR=([^|]+).*', '\\1') | default('unknown') }}"
        server_xml: "{{ data_line | regex_replace('.*SERVER_XML=([^|]+).*', '\\1') | default('unknown') }}"
        server_type: "{{ data_line | regex_replace('.*SERVER_TYPE=([^|]+).*', '\\1') | default('appserver') }}"
        jvm_heap: "{{ data_line | regex_replace('.*JVM_HEAP=([^|]+).*', '\\1') | default('unknown') }}"
        version: "{{ installation_map[was_home].version | default('unknown') }}"
        product: "{{ installation_map[was_home].product | default('WebSphere Application Server') }}"
        pids_array: "{{ [pid_raw | int] if pid_raw and pid_raw != '' else [] }}"
        ports_array: "{{ ports_raw.split(',') | map('int') | list if ports_raw and ports_raw != 'none' and ports_raw != '' else [] }}"
        config_ports_array: "{{ config_ports_raw.split(',') | map('int') | list if config_ports_raw and config_ports_raw != 'none' and config_ports_raw != '' else [] }}"
        json_instance:
          name: "{{ server_name }}"
          version: "{{ version }}"
          product: "{{ product }}"
          server_type: "{{ server_type }}"
          status: "{{ status }}"
          ports: "{{ ports_array }}"
          config_ports: "{{ config_ports_array }}"
          pids: "{{ pids_array }}"
          cell_name: "{{ cell_name }}"
          node_name: "{{ node_name }}"
          profile_name: "{{ profile_name }}"
          profile_path: ["{{ profile_path }}"]
          was_home: "{{ was_home }}"
          config_path: ["{{ server_xml }}"]
          log_path: ["{{ log_dir }}"]
          run_user: "{{ run_user }}"
          jvm_settings: "{{ jvm_heap }}"
          type: "APPSERVER"
      loop: "{{ was_server_details.results }}"
      when:
        - was_server_details is defined
        - was_server_details.results is defined
        - item.stdout is defined
        - item.stdout != ''

    # ========================================
    # STEP 7: BUILD FINAL JSON STRUCTURE
    # ========================================
    - name: Build final JSON structure
      set_fact:
        ibm_was_discovery_json:
          hostname: "{{ inventory_hostname }}"
          ip_address: "{{ ansible_default_ipv4.address | default('N/A') }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          discovery_timestamp: "{{ ansible_date_time.iso8601 }}"
          discovery: "{{ discovery_array | default([]) }}"

    - name: Display JSON output
      debug:
        msg: "IBM WebSphere Discovery: {{ discovery_array | length }} instance(s) found on {{ inventory_hostname }}"